language: node_js
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
after_success:
- yarn coverage
deploy:
  provider: npm
  email: toxictoxer@gmail.com
  on:
    tags: true
    repo: chinjs/chin-plugin-unified
    branch: publish
  api_key:
    secure: vIvHTCIJL+9FjhnxtPYws60ULqt36RR8JvoVV4EqZqbHtVomD+uiAvhVMWLG63x91ctraOsWuBn/+FM5lDcMQ2U3HM2Bvd7w7k6yBIgTZwmciLi2KrSdbf1VINkD1Gf+yFbxkgzxmu/1LNQKha40OR6wgBe74ZORwDsGUSaZ+9qmXUnt4bnX4sFV1E8O4dLg5TnulOgtlkrNRaS2d2wz0EfZRDkI12NSYNz64UzkkcPI91WP6xfgFSxsclsDPeW8s0EtfxuLZnvXvYAwwNPjbq1szaPHWiIp0wFAYgPxx/yYUbLSY2rHVPf4HsHT2q1pvoCMFKRIk0ITvXo4x0x2PWKSIA60TGRcMFMHqOO5uVexOWqrmpoOVyz98XYWt6ZLynY7zMjEyKhF9Ivc/Se1AJKnhXtUFQPZATCUAdd/4LfgNsTrXDhTwxbqNeTW2ywqLqZ0m5QjPZPU3dW20eJgA+X8uWA1wGSzAa79I6kLtvEt2hVtchtZYr8LBd92D8suN5OXhycNELmHnAiMYATqqnh78z73wXv1fxHphl2Kcr32DgdAOS3maLGUN2EC4UqHPqP6QVQ48WMrQgo1/SwhkaxXHndJCSM2+5ru38in7WuOgfhbUVK1RX2wBNf5bwO8sD3cccapN4mHA31K1EG5oAPVsLNiaiiC+VQUdNhOexY=
